# Generated by Django 5.2.3 on 2026-01-31 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('subject', '0002_subjectassign_discipline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectassign',
            options={'ordering': ['teacher', 'subject'], 'verbose_name': 'Subject Assignment', 'verbose_name_plural': 'Subject Assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'semester', 'desciplain')},
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Select subjects that must be completed before taking this subject', related_name='is_prerequisite_for', to='subject.subject', verbose_name='Prerequisite Subjects'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit_hours',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of credit hours for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Credit Hours'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='desciplain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Academic.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Enter the full name of the subject', max_length=100, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], default='core', max_length=10, verbose_name='Subject Type'),
        ),
        migrations.AlterField(
            model_name='subjectassign',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.discipline', verbose_name='Discipline'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
    ]
