# Generated by Django 5.2.3 on 2026-02-01 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('subject', '0003_alter_subjectassign_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['semester__number', 'code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Select the section for this subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Academic.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(help_text='Select which semester this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Academic.semester', verbose_name='Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'semester', 'desciplain', 'section')},
        ),
    ]
