# Generated by Django 6.0.2 on 2026-03-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('subject', '0004_alter_subject_options_alter_subject_unique_together_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectassign',
            unique_together={('teacher', 'subject', 'batch', 'semester')},
        ),
        migrations.AddField(
            model_name='subjectassign',
            name='sections',
            field=models.ManyToManyField(help_text='Select multiple sections for this assignment', related_name='subject_assignments', to='Academic.section', verbose_name='Sections'),
        ),
        migrations.RemoveField(
            model_name='subjectassign',
            name='section',
        ),
    ]
