# Generated by Django 5.2.3 on 2026-01-27 15:28

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0002_subjectassign_discipline'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Configuration Name')),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum percentage required to be eligible for exams', max_digits=5, verbose_name='Minimum Attendance Percentage')),
                ('auto_calculate_summary', models.BooleanField(default=True, help_text='Automatically calculate daily summaries', verbose_name='Auto Calculate Summary')),
                ('send_notifications', models.BooleanField(default=True, help_text='Send notifications for low attendance', verbose_name='Send Notifications')),
                ('notification_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage below which notifications are sent', max_digits=5, verbose_name='Notification Threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Configuration',
                'verbose_name_plural': 'Attendance Configurations',
            },
        ),
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LOW_ATTENDANCE', 'Low Attendance Alert'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('SYSTEM', 'System Notification')], max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=200, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to='student.student', verbose_name='Student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_notifications', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Attendance Notification',
                'verbose_name_plural': 'Attendance Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Attendance Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Attendance Time')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='P', max_length=1, verbose_name='Attendance Status')),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes about attendance', null=True, verbose_name='Remarks')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Academic.batch', verbose_name='Batch')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Academic.discipline', verbose_name='Discipline')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='teachers.teacher', verbose_name='Marked By')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Academic.section', verbose_name='Section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Academic.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='subject.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_attendances', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-time', 'student'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx'), models.Index(fields=['subject', 'date'], name='attendance__subject_1e77cb_idx'), models.Index(fields=['batch', 'semester', 'section', 'date'], name='attendance__batch_i_ce4eac_idx')],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True, verbose_name='Date')),
                ('total_students', models.IntegerField(default=0, verbose_name='Total Students')),
                ('present_count', models.IntegerField(default=0, verbose_name='Present Count')),
                ('absent_count', models.IntegerField(default=0, verbose_name='Absent Count')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Attendance Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='Academic.batch', verbose_name='Batch')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='Academic.discipline', verbose_name='Discipline')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='Academic.section', verbose_name='Section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='Academic.semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='subject.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Daily Attendance Summary',
                'verbose_name_plural': 'Daily Attendance Summaries',
                'ordering': ['-date', 'batch', 'semester', 'section'],
                'unique_together': {('date', 'batch', 'semester', 'section', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Year')),
                ('total_days', models.IntegerField(default=0, verbose_name='Total Days')),
                ('present_days', models.IntegerField(default=0, verbose_name='Present Days')),
                ('absent_days', models.IntegerField(default=0, verbose_name='Absent Days')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Attendance Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='Academic.batch', verbose_name='Batch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='Academic.section', verbose_name='Section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='Academic.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='student.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Monthly Attendance Report',
                'verbose_name_plural': 'Monthly Attendance Reports',
                'ordering': ['-year', '-month', 'student'],
                'unique_together': {('month', 'year', 'student')},
            },
        ),
    ]
