# Generated by Django 6.0.2 on 2026-02-24 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0004_alter_subject_options_alter_subject_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed'), ('used', 'Used'), ('expired', 'Expired')], default='generated', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tokens/qrcodes/')),
                ('attendance_short', models.JSONField(blank=True, default=dict)),
                ('fee_defaulters', models.JSONField(blank=True, default=dict)),
                ('prerequisite_missing', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.batch')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.discipline')),
                ('eligible_subjects', models.ManyToManyField(blank=True, related_name='tokens', to='subject.subject')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_tokens', to='student.student')),
            ],
            options={
                'verbose_name': 'Exam Token',
                'verbose_name_plural': 'Exam Tokens',
                'ordering': ['-issue_date', 'student'],
                'unique_together': {('student', 'semester', 'issue_date')},
            },
        ),
    ]
