# Generated by Django 6.0.2 on 2026-02-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0004_alter_subject_options_alter_subject_unique_together_and_more'),
        ('teachers', '0001_initial'),
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtoken',
            options={'ordering': ['-issue_date', 'student']},
        ),
        migrations.AddField(
            model_name='examtoken',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tokens', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='examtoken',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examtoken',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examtoken',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tokens', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tokens/qrcodes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('printed', 'Printed'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('verified', 'Verified'), ('pending', 'Pending Verification')], db_index=True, default='generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='token_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='examtoken',
            index=models.Index(fields=['status', 'valid_until'], name='token_app_e_status_b0bc74_idx'),
        ),
        migrations.AddIndex(
            model_name='examtoken',
            index=models.Index(fields=['student', 'status'], name='token_app_e_student_1af161_idx'),
        ),
    ]
