# Generated by Django 5.2.3 on 2026-02-07 07:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('attendance', '0001_initial'),
        ('exam_mang', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0004_alter_subject_options_alter_subject_unique_together_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=50, unique=True, verbose_name='Token Number')),
                ('token_type', models.CharField(choices=[('PERMISSION', 'Permission'), ('MAKEUP', 'Make-up'), ('ATTENDANCE', 'Attendance Correction'), ('EXAM', 'Exam Token'), ('FEE', 'Fee Extension'), ('LIBRARY', 'Library'), ('OTHER', 'Other')], max_length=20, verbose_name='Token Type')),
                ('title', models.CharField(max_length=200, verbose_name='Token Title')),
                ('description', models.TextField(help_text='Detailed description of the token request', verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority Level')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Created Date')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('due_date', models.DateField(help_text='Date by which this token should be processed', verbose_name='Due Date')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Resolved Date')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejecting the token', null=True, verbose_name='Rejection Reason')),
                ('attachment', models.FileField(blank=True, help_text='Upload supporting documents if any', null=True, upload_to='token_attachments/', verbose_name='Attachment')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent Request')),
                ('requires_parent_approval', models.BooleanField(default=False, verbose_name='Requires Parent Approval')),
                ('parent_approved', models.BooleanField(default=False, verbose_name='Parent Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tokens', to='teachers.teacher', verbose_name='Approved By')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tokens', to='teachers.teacher', verbose_name='Assigned To')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='Academic.batch', verbose_name='Batch')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='Academic.discipline', verbose_name='Discipline')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='Academic.section', verbose_name='Section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='Academic.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='student.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-submitted_at', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TokenCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='Default Priority')),
                ('sla_days', models.PositiveIntegerField(default=7, help_text='Service Level Agreement - Days to resolve', verbose_name='SLA Days')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requires Approval')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Category',
                'verbose_name_plural': 'Token Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TokenRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rule Name')),
                ('description', models.TextField(verbose_name='Rule Description')),
                ('condition', models.TextField(help_text='Python condition to evaluate (returns True/False)', verbose_name='Condition')),
                ('action', models.TextField(help_text='Python code to execute if condition is True', verbose_name='Action')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Rule',
                'verbose_name_plural': 'Token Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TokenStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total Tokens')),
                ('pending_tokens', models.PositiveIntegerField(default=0, verbose_name='Pending Tokens')),
                ('resolved_tokens', models.PositiveIntegerField(default=0, verbose_name='Resolved Tokens')),
                ('overdue_tokens', models.PositiveIntegerField(default=0, verbose_name='Overdue Tokens')),
                ('avg_resolution_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Average Resolution Time (hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Statistics',
                'verbose_name_plural': 'Token Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PermissionToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qr_tokens.token')),
                ('permission_type', models.CharField(choices=[('LEAVE', 'Leave Request'), ('LATE_ENTRY', 'Late Entry'), ('EARLY_EXIT', 'Early Exit'), ('SPECIAL_PERMISSION', 'Special Permission'), ('OFF_CAMPUS', 'Off Campus Permission')], max_length=50, verbose_name='Permission Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('reason_for_permission', models.TextField(verbose_name='Reason for Permission')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Phone')),
                ('destination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination')),
                ('guardian_approval', models.BooleanField(default=False, verbose_name='Guardian Approval')),
            ],
            options={
                'verbose_name': 'Permission Token',
                'verbose_name_plural': 'Permission Tokens',
            },
            bases=('qr_tokens.token',),
        ),
        migrations.CreateModel(
            name='TokenComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_internal_note', models.BooleanField(default=False, help_text='If True, comment is not visible to student', verbose_name='Internal Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_comments', to='teachers.teacher', verbose_name='Author')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qr_tokens.token', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Token Comment',
                'verbose_name_plural': 'Token Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('ASSIGNMENT', 'Assignment'), ('COMMENT', 'Comment'), ('OVERDUE', 'Overdue'), ('REMINDER', 'Reminder')], max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=200, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_notifications', to='student.student', verbose_name='Recipient')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='qr_tokens.token', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Token Notification',
                'verbose_name_plural': 'Token Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100, verbose_name='Step Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20, verbose_name='Step Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Step Notes')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Step Order')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required Step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to='teachers.teacher', verbose_name='Assigned To')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workflow_tasks', to='teachers.teacher', verbose_name='Completed By')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='qr_tokens.token', verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Token Workflow Step',
                'verbose_name_plural': 'Token Workflow Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qr_tokens.token')),
                ('attendance_date', models.DateField(verbose_name='Attendance Date')),
                ('original_status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], help_text='Original attendance status', max_length=1, verbose_name='Original Status')),
                ('requested_status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], help_text='Requested attendance status', max_length=1, verbose_name='Requested Status')),
                ('reason_for_change', models.TextField(help_text='Reason for requesting attendance status change', verbose_name='Reason for Change')),
                ('supporting_evidence', models.TextField(blank=True, help_text='Any supporting evidence for the request', null=True, verbose_name='Supporting Evidence')),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendance', verbose_name='Attendance Record')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_tokens', to='subject.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Attendance Token',
                'verbose_name_plural': 'Attendance Tokens',
            },
            bases=('qr_tokens.token',),
        ),
        migrations.CreateModel(
            name='ExamToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qr_tokens.token')),
                ('request_type', models.CharField(choices=[('MAKEUP_EXAM', 'Make-up Exam'), ('EXAM_RESCHEDULE', 'Exam Reschedule'), ('SPECIAL_ASSISTANCE', 'Special Assistance'), ('OTHER_EXAM_REQUEST', 'Other Exam Request')], max_length=50, verbose_name='Request Type')),
                ('requested_exam_date', models.DateField(blank=True, null=True, verbose_name='Requested Exam Date')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='medical_certificates/', verbose_name='Medical Certificate')),
                ('previous_attempts', models.PositiveIntegerField(default=0, verbose_name='Previous Attempts')),
                ('is_medical_case', models.BooleanField(default=False, verbose_name='Medical Case')),
                ('doctor_notes', models.TextField(blank=True, null=True, verbose_name="Doctor's Notes")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='exam_mang.exam', verbose_name='Exam')),
                ('subject_mark_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_tokens', to='exam_mang.subjectmarkcomponents', verbose_name='Subject Mark Component')),
            ],
            options={
                'verbose_name': 'Exam Token',
                'verbose_name_plural': 'Exam Tokens',
            },
            bases=('qr_tokens.token',),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token_number'], name='qr_tokens_t_token_n_43864f_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['student', 'status'], name='qr_tokens_t_student_3be419_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token_type', 'status'], name='qr_tokens_t_token_t_3fd2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['assigned_to', 'status'], name='qr_tokens_t_assigne_564924_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['due_date', 'status'], name='qr_tokens_t_due_dat_b573ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenworkflow',
            unique_together={('token', 'step_name')},
        ),
    ]
