# Generated by Django 5.2.3 on 2025-10-30 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the subject', max_length=20, verbose_name='Subject Name')),
                ('code', models.CharField(help_text='Short code for the subject (e.g., CS101)', max_length=20, unique=True, verbose_name='Subject Code')),
                ('subject_id', models.CharField(help_text='Unique identifier for the subject', max_length=20, unique=True, verbose_name='Subject ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')], help_text='Select which semester this subject belongs to', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Semester')),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('general', 'General')], default='elective', max_length=10, verbose_name='Subject Type')),
                ('credit_hours', models.PositiveSmallIntegerField(default=6, help_text='Number of credit hours for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Credit Hours')),
                ('description', models.TextField(blank=True, help_text='Optional description about the subject', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['semester', 'code'],
                'unique_together': {('code', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Assigned Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Assignment')),
                ('batch', models.ForeignKey(help_text='Select the batch for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='student.batch', verbose_name='Batch')),
                ('section', models.ForeignKey(help_text='Select the section for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='student.section', verbose_name='Section')),
                ('semester', models.ForeignKey(help_text='Select the semester for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='student.semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(help_text='Select the subject to assign', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='subjects.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(help_text='Select the teacher for this subject', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Subject Assignment',
                'verbose_name_plural': 'Subject Assignments',
                'ordering': ['teacher', 'subject'],
                'unique_together': {('teacher', 'subject', 'batch', 'semester', 'section')},
            },
        ),
    ]
