# Generated by Django 5.2.3 on 2025-10-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_discipline'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Assigned Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active SubjectAssign')),
                ('batch', models.ForeignKey(help_text='Select the batch for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='student.batch', verbose_name='Batch')),
                ('section', models.ForeignKey(help_text='Select the section for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='student.section', verbose_name='Section')),
                ('semester', models.ForeignKey(help_text='Select the semester for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='student.semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(help_text='Select the subject to assign', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='subjects.subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(help_text='Select the teacher for this subject', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': ' SubjectAssign',
                'verbose_name_plural': 'SubjectAssign ',
                'ordering': ['teacher', 'subject'],
                'unique_together': {('teacher', 'subject', 'batch', 'semester', 'section')},
            },
        ),
        migrations.DeleteModel(
            name='SubjectAssignment',
        ),
    ]
