# Generated by Django 5.2.3 on 2025-10-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_discipline'),
        ('subjects', '0002_subjectassign_delete_subjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='desciplain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.discipline'),
            preserve_default=False,
        ),
    ]
