# Generated by Django 5.2.3 on 2025-10-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('ufm', 'Unfair Means'), ('ddc', 'Department Discipline Committee')], max_length=10)),
                ('fine', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
