# Generated by Django 5.2.3 on 2025-11-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddc', '0002_initial'),
        ('student', '0008_alter_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Disciplines',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.discipline'),
            preserve_default=False,
        ),
    ]
