# Generated by Django 6.0.3 on 2026-03-22 10:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('subject', '0005_alter_subjectassign_unique_together_and_more'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('auditorium', 'Auditorium'), ('seminar', 'Seminar Hall')], default='classroom', max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.IntegerField(default=0)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('is_lab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_number', models.IntegerField(help_text='Order of slot in the day (1,2,3...)')),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='Academic.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='Academic.discipline')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='Academic.semester')),
            ],
            options={
                'unique_together': {('discipline', 'batch', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('algorithm_used', models.CharField(default='genetic', max_length=50)),
                ('fitness_score', models.FloatField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('generation_data', models.JSONField(help_text='Store the complete timetable data as JSON')),
                ('stats', models.JSONField(default=dict, help_text='Generation statistics')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='timetable.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('no_overlap_teacher', 'No Teacher Overlap'), ('no_overlap_room', 'No Room Overlap'), ('no_overlap_section', 'No Section Overlap'), ('teacher_max_hours', 'Teacher Max Hours'), ('subject_consecutive', 'Subject Consecutive Limit'), ('preferred_time', 'Preferred Time'), ('avoid_time', 'Avoid Time')], max_length=30)),
                ('day', models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('value', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Higher number = higher priority')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='timetable.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.CharField(choices=[('every', 'Every Week'), ('odd', 'Odd Weeks'), ('even', 'Even Weeks'), ('alternate', 'Alternate Weeks'), ('once', 'Once')], default='every', max_length=20)),
                ('start_week', models.IntegerField(default=1, help_text='Starting week number (1-16)')),
                ('end_week', models.IntegerField(default=16, help_text='Ending week number (1-16)')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='timetable.timetableentry')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='Academic.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subject.subject')),
                ('subject_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subject.subjectassign')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='teachers.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetable')),
            ],
            options={
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['time_slot__day', 'time_slot__start_time'],
                'unique_together': {('timetable', 'teacher', 'time_slot', 'section')},
            },
        ),
        migrations.CreateModel(
            name='TimetableConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('warning', 'Warning')], max_length=20)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='timetable.timetable')),
                ('entry1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='timetable.timetableentry')),
                ('entry2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='timetable.timetableentry')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='teachers.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot')),
            ],
            options={
                'unique_together': {('teacher', 'time_slot', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='timetable.room')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot')),
            ],
            options={
                'unique_together': {('room', 'time_slot', 'semester')},
            },
        ),
    ]
