# Generated by Django 5.2.3 on 2025-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BS', 'BS'), ('MS', 'MS'), ('PhD', 'PhD')], max_length=10)),
                ('field', models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('DS', 'Data Science'), ('CS', 'CYBER SECURITY'), ('DA', 'DATA SCIENCE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'unique_together': {('program', 'field')},
            },
        ),
    ]
