# Generated by Django 5.2.3 on 2025-10-30 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.discipline'),
            preserve_default=False,
        ),
    ]
