# Generated by Django 5.2.3 on 2025-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='field',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Data Science', 'Data Science'), ('CYBER SECURITY', 'CYBER SECURITY'), ('DATA SCIENCE', 'DATA SCIENCE')], max_length=50),
        ),
    ]
