# Generated by Django 5.2.3 on 2025-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_discipline_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='field',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('ARTIFICIAL INTELLIGENCE', 'ARTIFICIAL INTELLIGENCE'), ('CYBER SECURITY', 'CYBER SECURITY'), ('DATA SCIENCE', 'DATA SCIENCE')], max_length=50),
        ),
    ]
