# Generated by Django 5.2.3 on 2025-11-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.discipline'),
            preserve_default=False,
        ),
    ]
