# Generated by Django 5.2.3 on 2025-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_batch_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
