# Generated by Django 5.2.3 on 2025-12-26 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BS', 'BS'), ('MS', 'MS'), ('PhD', 'PhD')], max_length=40)),
                ('field', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Cyber Security', 'Cyber Security'), ('Data Science', 'Data Science')], max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Disciplines',
                'unique_together': {('program', 'field')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start_session', models.CharField(max_length=10)),
                ('end_session', models.CharField(max_length=10)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.batch')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.discipline')),
            ],
            options={
                'unique_together': {('name', 'batch')},
            },
        ),
    ]
