# Generated by Django 6.0.2 on 2026-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
