# Generated by Django 5.2.3 on 2025-12-26 15:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tuition Fee')),
                ('fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Late Fine')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount Paid')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Balance Due')),
                ('is_overdue', models.BooleanField(default=False)),
                ('grace_period', models.PositiveIntegerField(default=5, help_text='Grace period in days')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.batch')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.discipline')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Student Fee',
                'verbose_name_plural': 'Student Fees',
                'ordering': ['-due_date'],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ClearFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('cleared_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online Payment')], default='Cash', max_length=20)),
                ('collector_name', models.CharField(choices=[('name1', 'name1'), ('name2', 'name2'), ('name3', 'name3')], default=None, max_length=50)),
                ('cleared_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('installment_number', models.PositiveIntegerField(default=1, help_text='Installment number for this payment')),
                ('upload_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_records', to='fee_system.uploadfee')),
            ],
            options={
                'ordering': ['cleared_date'],
                'unique_together': {('upload_fee', 'installment_number')},
            },
        ),
    ]
