# Generated by Django 5.2.3 on 2025-11-12 10:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0006_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_option', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], help_text='Select the semester this fee applies to', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter any fine amount (default is 5000)', max_digits=10)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['batch', 'semester', 'section', 'student'],
                'unique_together': {('student', 'semester_option')},
            },
        ),
        migrations.CreateModel(
            name='ClearFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('cleared_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online Payment')], default='Cash', max_length=20)),
                ('collector_name', models.CharField(choices=[('name1', 'name1'), ('name2', 'name2'), ('name3', 'name3')], default=None, max_length=50)),
                ('cleared_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('upload_fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clear_record', to='fee_system.uploadfee')),
            ],
            options={
                'ordering': ['cleared_date'],
            },
        ),
    ]
