# Generated by Django 5.2.3 on 2025-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_system', '0002_uploadfee_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
