# Generated by Django 5.2.3 on 2025-12-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_system', '0003_uploadfee_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
