# Generated by Django 5.2.3 on 2025-12-21 13:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_system', '0004_alter_uploadfee_amount'),
        ('student', '0008_alter_batch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfee',
            options={'ordering': ['-due_date'], 'verbose_name': 'Student Fee', 'verbose_name_plural': 'Student Fees'},
        ),
        migrations.AlterUniqueTogether(
            name='uploadfee',
            unique_together={('student', 'semester')},
        ),
        migrations.AddField(
            model_name='clearfee',
            name='installment_number',
            field=models.PositiveIntegerField(default=1, help_text='Installment number for this payment'),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='grace_period',
            field=models.PositiveIntegerField(default=5, help_text='Grace period in days'),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Balance Due'),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='upload_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_records', to='fee_system.uploadfee'),
        ),
        migrations.AlterField(
            model_name='uploadfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tuition Fee'),
        ),
        migrations.AlterField(
            model_name='uploadfee',
            name='due_date',
    field=models.DateField(default='2024-12-21'),
                            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfee',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Late Fine'),
        ),
        migrations.AlterUniqueTogether(
            name='clearfee',
            unique_together={('upload_fee', 'installment_number')},
        ),
        migrations.RemoveField(
            model_name='uploadfee',
            name='semester_option',
        ),
    ]
