# Generated by Django 5.2.3 on 2025-12-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_system', '0005_alter_clearfee_options_remove_clearfee_cleared_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearfee',
            options={'ordering': ['cleared_date']},
        ),
        migrations.RemoveField(
            model_name='clearfee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadfee',
            name='status',
        ),
        migrations.AddField(
            model_name='clearfee',
            name='cleared_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='collector_name',
            field=models.CharField(choices=[('name1', 'name1'), ('name2', 'name2'), ('name3', 'name3')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online Payment')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='upload_fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clear_record', to='fee_system.uploadfee'),
        ),
    ]
