# Generated by Django 5.2.3 on 2025-12-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_system', '0006_alter_clearfee_options_remove_clearfee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearfee',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='clearfee',
            name='cleared_date',
        ),
        migrations.AddField(
            model_name='clearfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='collector_name',
            field=models.CharField(choices=[('name1', 'Name 1'), ('name2', 'Name 2'), ('name3', 'Name 3'), ('other', 'Other')], default='name1', max_length=50),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online Payment'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='upload_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_records', to='fee_system.uploadfee'),
        ),
    ]
