# Generated by Django 5.2.3 on 2025-12-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_system', '0008_alter_clearfee_options_remove_clearfee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearfee',
            name='installment_number',
            field=models.PositiveIntegerField(default=1, help_text='Installment number for this payment'),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='uploadfee',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clearfee',
            name='upload_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_records', to='fee_system.uploadfee'),
        ),
        migrations.AlterUniqueTogether(
            name='clearfee',
            unique_together={('upload_fee', 'installment_number')},
        ),
    ]
