# Generated by Django 5.2.3 on 2025-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_system', '0009_clearfee_installment_number_uploadfee_is_fully_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearfee',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
