# Generated by Django 6.0.2 on 2026-03-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
    ]
