# Generated by Django 5.2.3 on 2025-11-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('roll_noid', models.CharField(max_length=40)),
                ('contect_number', models.CharField(max_length=50)),
            ],
        ),
    ]
