# Generated by Django 5.2.3 on 2025-12-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addstudent',
        ),
    ]
