# Generated by Django 5.2.3 on 2026-01-24 10:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academic', '0001_initial'),
        ('student', '0001_initial'),
        ('subject', '0002_subjectassign_discipline'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMarkComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026-2027', max_length=9)),
                ('subject_type', models.CharField(default='theory', max_length=20)),
                ('mid_term_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('final_term_percentage', models.DecimalField(decimal_places=2, default=65.0, max_digits=5)),
                ('quiz_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('assignment_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('presentation_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('lab_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('viva_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('internal_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='Total internal marks (quiz + assignment + presentation + attendance)', max_digits=5)),
                ('total_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Any notes about mark distribution')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.batch')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.discipline')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_components', to='subject.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_mark_components', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Subject Mark Distribution',
                'verbose_name_plural': 'Subject Mark Distributions',
                'unique_together': {('subject', 'teacher', 'semester', 'batch', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('final', 'Final'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('presentation', 'Presentation'), ('lab', 'Lab'), ('viva', 'Viva'), ('attendance', 'Attendance')], max_length=20)),
                ('exam_date', models.DateField(default=django.utils.timezone.now)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, help_text='Passing marks (default: 40% of total marks)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(default=False)),
                ('weightage_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage weightage of this exam in overall subject marks', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('subject_mark_component', models.ForeignKey(help_text='Select subject mark distribution configuration', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exam_mang.subjectmarkcomponents')),
            ],
            options={
                'ordering': ['-exam_date'],
                'unique_together': {('exam_type', 'subject_mark_component')},
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_number', models.CharField(max_length=50, unique=True)),
                ('transcript_type', models.CharField(choices=[('official', 'Official'), ('unofficial', 'Unofficial'), ('provisional', 'Provisional')], max_length=20)),
                ('issue_date', models.DateField()),
                ('semester_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_credits_attempted', models.PositiveIntegerField(default=0)),
                ('total_credits_earned', models.PositiveIntegerField()),
                ('total_quality_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('university_name', models.CharField(blank=True, max_length=200)),
                ('department_name', models.CharField(blank=True, max_length=200)),
                ('program_name', models.CharField(blank=True, max_length=200)),
                ('is_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='student.student')),
            ],
            options={
                'verbose_name': 'Academic Transcript',
                'verbose_name_plural': 'Academic Transcripts',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weighted_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Marks after applying weightage percentage', max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+ (4.00)'), ('A', 'A (4.00)'), ('A-', 'A- (3.67)'), ('B+', 'B+ (3.33)'), ('B', 'B (3.00)'), ('B-', 'B- (2.67)'), ('C+', 'C+ (2.33)'), ('C', 'C (2.00)'), ('D', 'D (1.67)'), ('F', 'F (0.00)')], max_length=2, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam_mang.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='student.student')),
            ],
            options={
                'ordering': ['student__student_id'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SubjectComprehensiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_term_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('final_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quiz_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('assignment_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('presentation_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('lab_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('viva_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('attendance_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+ (4.00)'), ('A', 'A (4.00)'), ('A-', 'A- (3.67)'), ('B+', 'B+ (3.33)'), ('B', 'B (3.00)'), ('B-', 'B- (2.67)'), ('C+', 'C+ (2.33)'), ('C', 'C (2.00)'), ('D', 'D (1.67)'), ('F', 'F (0.00)')], max_length=2, null=True)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('quality_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_results', to='student.student')),
                ('subject_mark_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_results', to='exam_mang.subjectmarkcomponents')),
            ],
            options={
                'verbose_name': 'Comprehensive Subject Result',
                'verbose_name_plural': 'Comprehensive Subject Results',
                'ordering': ['subject_mark_component__semester', 'subject_mark_component__subject__code'],
                'unique_together': {('student', 'subject_mark_component')},
            },
        ),
    ]
